#theme: jekyll-theme-tactile
remote_theme: jekyll/minima
title: Brent Farris' Website
description: Mostly about computer science stuff
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
titles_from_headings:
  enabled:     false
  strip_title: true
  collections: false
