#theme: jekyll-theme-tactile
remote_theme: BrentFarris/minima
title: Brent's Website
description: A personal log about things I like in computer programming, art, electronics, and other hobbies.\n\nAll code on my website is free for anyone to use (public domain). All that I ask is that you display attribution ("Brent Farris") in source code comments and/or in credits.
tagline: Some Assembly required
author: Brent Farris
email: RetroScience@aquamail.net
google_analytics: UA-154143529-1
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
titles_from_headings:
  enabled:     false
  strip_title: true
  collections: false
highlighter: rouge
