#theme: jekyll-theme-tactile
remote_theme: BrentFarris/minima
title: Brent's Website
description: Only poor craftsmen blame their tools
tagline: Some Assembly required
author: Brent Farris
email: RetroScience@aquamail.net
google_analytics: UA-154143529-1
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
titles_from_headings:
  enabled:     false
  strip_title: true
  collections: false
